play=1;
axHndl=gca;
figNumber=gcf;
hndlList=get(figNumber,'UserData');

set(figNumber,'Backingstore','off');

% The graphics axis limits are set to values known 
% to contain the solution.
set(axHndl, ...
   'XLim',[0 40],'YLim',[-35 10],'ZLim',[-10 40], ...
   'Userdata',play, ...
   'XTick',[],'YTick',[],'ZTick',[], ...
   'Drawmode','fast', ...
   'Visible','on', ...
   'NextPlot','add', ...
   'Userdata',play, ...
   'View',[-37.5,30]);

axis([-1 1 -1 1 -1 1])
axis square
grid on
xlabel('x-ECI')
ylabel('y-ECI')
zlabel('z-ECI')

cla;
bodyx = line( ...
   'color','r', ...
   'LineStyle','-', ...
   'LineWidth',3, ...
   'erase','xor', ...
   'xdata',[0 0],'ydata',[0 0],'zdata',[0 0]);
bodyy = line( ...
   'color','g', ...
   'LineStyle','-', ...
   'LineWidth',3, ...
   'erase','xor', ...
   'xdata',[0 0],'ydata',[0 0],'zdata',[0 0]);
bodyz = line( ...
   'color','b', ...
   'LineStyle','-', ...
   'LineWidth',3, ...
   'erase','xor', ...
   'xdata',[0 0],'ydata',[0 0],'zdata',[0 0]);

h_temp=legend(['x-Body';'y-Body';'z-Body']); set(h_temp,'FontSize',12);
h_temp=title('Lage des Körpers (Eingabetaste zum Start)');set(h_temp,'FontSize',14);
 
view(135,25);
drawnow;

